name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: List files
        run: ls -al src/main/resources

      - name: Create application-local.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-local.yml

      - name: Build Docker image
        run: docker build -t baff_be/baff_be .
